version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    # Netzwerkkonfiguration für Telegram Bot
    # network_mode: "bridge"
    environment:
      - PYTHONUNBUFFERED=1
      - GIT_REPO_URL=https://github.com/tappi287/recipe_agent.git
    volumes:
      - repo_data:/app/repo
      - playwright_cache:/root/.cache/ms-playwright

volumes:
  repo_data:
    # Dieses Volume speichert das geklonte Repository
  playwright_cache:
    # Dieses Volume speichert die Playwright Browser-Binaries
