services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    # Netzwerkkonfiguration für Telegram Bot
    # network_mode: "bridge"
    environment:
      - PYTHONUNBUFFERED=1
      - GIT_REPO_URL=https://github.com/tappi287/recipe_agent.git
      - WEB_APP_PORT=2020
    volumes:
      - repo_data:/app/repo
      - playwright_cache:/root/.cache/ms-playwright
    # Point to your reverse proxy network
    networks:
      web:
        ipv4_address: 172.18.0.20
        ipv6_address: fd3d:ab00:83b3::20

volumes:
  repo_data:
    # Dieses Volume speichert das geklonte Repository
  playwright_cache:
    # Dieses Volume speichert die Playwright Browser-Binaries

networks:
  web:
    external: true
